using System.Text;

namespace PM
{
    public enum LabelType
    {
        EMPTY_LABEL,

        OPERATOR_SOURCE_NAME_IN_PROCESSING,

        OPERATOR_SOURCE_UKRTELECOM_REVEALED,
        OPERATOR_SOURCE_KIEVSTAR_REVEALED,
        OPERATOR_SOURCE_VODAFON_REVEALED,
        OPERATOR_SOURCE_UKRTELECOM_PROCESSED,
        OPERATOR_SOURCE_KIEVSTAR_PROCESSED,
        OPERATOR_SOURCE_VODAFON_PROCESSED,


        OPERATOR_SOURCE_UKRTELECOM_PROCESSED_SUCCESFULLY,
        OPERATOR_SOURCE_KIEVSTAR_PROCESSED_SUCCESFULLY,
        OPERATOR_SOURCE_VODAFON_PROCESSED_SUCCESFULLY,

        OPERATOR_SOURCE_UKRTELECOM_PROCESSED_UNSUCCESFULLY,
        OPERATOR_SOURCE_KIEVSTAR_PROCESSED_UNSUCCESFULLY,
        OPERATOR_SOURCE_VODAFON_PROCESSED_UNSUCCESFULLY,

        FIRST_PASS_INITIALIZED,
        FIRST_PASS_PROCESSING,
        FIRST_PASS_PASSED,
        SECOND_PASS_INITIALIZED,
        SECOND_PASS_PROCESSING,
        SECOND_PASS_PASSED,
        THIRD_PASS_INITIALIZED,
        THIRD_PASS_PROCESSING,
        THIRD_PASS_PASSED,

        PARSING_HEAD_OF_XLSX,
        PARCING_BODY_TABLE_OF_XLSX,

        PARCING_HEAD_OF_XLSX_INITIALIZED,
        PARCING_HEAD_OF_XLSX_PASSED,

        PARCING_BODY_TABLE_OF_XLSX_INITIALIZED,
        PARCING_BODY_TABLE_OF_XLSX_PASSED,

        INVOICE_DATE,

        RAW_DOCUMENT_NUMBER_ROW,
        RAW_DOCUMENT_NUMBER_COLUMN,
        RAW_ROW_SPLITTED_INTO_CELLS
    }
}


